language: java

script:
   - mvn evosuite:generate evosuite:export -Duse_separate_classloader=false jacoco:prepare-agent install jacoco:report

after_success:
  - bash <(curl -s https://codecov.io/bash)
